services:
  # 1. FastAPI Backend
  - type: web
    name: cardiosense-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        sync: false # You will fill this in the Render Dashboard
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false

  # 2. Streamlit Frontend
  - type: web
    name: cardiosense-frontend
    runtime: docker
    dockerContext: .
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: API_URL
        value: https://cardiosense-backend.onrender.com/predict
